Get smarter about options.

diff --git a/samtoc/samtoc b/samtoc/samtoc
--- a/samtoc/samtoc
+++ b/samtoc/samtoc
@@ -33,6 +33,9 @@ init-prog
 # Output file name.
 outputFile=''
 
+# Did we get `--out-dir`?
+gotOutDir=0
+
 # Whether to compile to binary.
 fullCompile='yes'
 
@@ -50,10 +53,12 @@ while [[ $1 != '' ]]; do
         exit
     elif [[ ${opt} == '--c-code' ]]; then
         fullCompile='no'
-    elif [[    ${opt} =~ ^--mode=(.*)
-            || ${opt} =~ ^--in-dir=(.*)
-            || ${opt} =~ ^--out-dir=(.*) ]]; then
+    elif [[    ${opt} =~ ^--mode=
+            || ${opt} =~ ^--in-dir= ]]; then
         moreArgs+=("${opt}")
+    elif [[ ${opt} =~ ^--out-dir= ]]; then
+        moreArgs+=("${opt}")
+        gotOutDir=1
     elif [[ ${opt} =~ ^--output=(.*) ]]; then
         outputFile="${BASH_REMATCH[1]}"
     elif [[ ${opt} =~ ^- ]]; then
@@ -69,15 +74,15 @@ unset opt
 if (( $# == 0 )); then
     echo 'Missing source file name.' 1>&2
     exit 1
-elif (( $# > 1 )); then
-    # Multiple source files.
+elif (( $# > 1 || gotOutDir )); then
+    # Multiple source files or `--out-dir` specified.
     fullCompile='no'
     if [[ ${outputFile} != '' ]]; then
-        echo 'Cannot specify --output with multiple sources.' 1>&2
+        echo 'Cannot specify --output with multiple sources or --out-dir.' 1>&2
         exit 1
     fi
 else
-    # Single source file.
+    # Single source file and no `--out-dir`.
     if [[ ${outputFile} == '' ]]; then
         if [[ ${fullCompile} == 'yes' ]]; then
             outputFile="${1%.sam*}.samb"
