Add build options to `samex`.

diff --git a/samex/samex b/samex/samex
--- a/samex/samex
+++ b/samex/samex
@@ -40,7 +40,13 @@ unset newProg
 #
 
 # Preferred runtime name option.
-runtimeOpt=()
+runtimeName=''
+
+# Whether to build a binary.
+build='no'
+
+# Whether to build with optimization.
+optimize='no'
 
 # Whether to time the run.
 timeRun='no'
@@ -54,13 +60,19 @@ while [[ $1 != '' ]]; do
         shift
         break
     elif [[ ${opt} == '--help' ]]; then
-        echo "${progName} [--runtime=<name>] [--time | --profile]"
+        echo "${progName} [--runtime=<name>]"
+        echo '    [--build] [--optimize] [--time | --profile]'
         exit
+    elif [[ ${opt} == '--build' ]]; then
+        build='yes'
+    elif [[ ${opt} == '--optimize' ]]; then
+        optimize='yes'
+        build='yes'
     elif [[ ${opt} == '--profile' ]]; then
         profileRun='yes'
         timeRun='no'
     elif [[ ${opt} =~ ^--runtime=(.*) ]]; then
-        runtimeOpt=("${opt}")
+        runtimeName="${BASH_REMATCH[1]}"
     elif [[ ${opt} == '--time' ]]; then
         timeRun='yes'
         profileRun='no'
@@ -78,6 +90,35 @@ unset opt
 #
 # Main script
 #
+
+# Build the binary, if requested.
+
+if [[ ${build} == 'yes' ]]; then
+    if [[ ${runtimeName} == '' ]]; then
+        echo 'No --runtime specified.' 1>&2
+        exit 1
+    fi
+
+    sourceDir="$(cd "${baseDir}/../.."; pwd)/samex-${runtimeName}"
+    if [[ ! -d "${sourceDir}" ]]; then
+        echo "Source directory not found: ${sourceDir}" 1>&2
+        exit 1
+    fi
+
+    buildOpts=()
+
+    if [[ ${optimize} == 'yes' ]]; then
+        buildOpts=(--optimize)
+    fi
+
+    echo "Building..."
+    "${sourceDir}/build" "${buildOpts[@]}" > /dev/null || exit 1
+fi
+
+runtimeOpt=()
+if [[ ${runtimeName} != '' ]]; then
+    runtimeOpt=(--runtime="${runtimeName}")
+fi
 
 name="$("${progDir}/find-samex" "${runtimeOpt[@]}" --bin)"
 if [[ $? != 0 ]]; then
