Try to actually handle gcc.

diff --git a/samex/bin/compile-samex-addon b/samex/bin/compile-samex-addon
--- a/samex/bin/compile-samex-addon
+++ b/samex/bin/compile-samex-addon
@@ -92,19 +92,27 @@ WHAT_CC="$(
     END     { print "unknown" }
     ')"
 
-if [[ ${WHAT_CC} != 'clang' ]]; then
-    echo 1>&2 "Sorry: Cannot use compiler: ${WHAT_CC}"
-    exit 1
-fi
-
 CC_PREFIX=("${CC}" -g)
 
-# Note: The GNU equivalent to `-dynamiclib` seems to be `-shared`, and
-# the equivalent to `-undefined dynamic_lookup` seems to be `-Ur`.
-COMPILE_LIB=(
-    "${CC_PREFIX[@]}"
-        -dynamiclib -undefined dynamic_lookup
-        -I"${includeDir}"
-)
+case "${WHAT_CC}" in
+    (clang)
+        COMPILE_LIB=(
+            "${CC_PREFIX[@]}"
+                -dynamiclib -undefined dynamic_lookup
+                -I"${includeDir}"
+        )
+        ;;
+    (gcc)
+        COMPILE_LIB=(
+            "${CC_PREFIX[@]}"
+                -shared -Ur
+                -I"${includeDir}"
+        )
+        ;;
+    (*)
+        echo 1>&2 "Sorry: Cannot use compiler: ${WHAT_CC}"
+        exit 1
+        ;;
+esac
 
 "${COMPILE_LIB[@]}" -o "${outputFile}" "$@"
