Initial work on dealing with different compiler toolchains.
* Notice if `${CC}` is set, and use it.
* Use `--version` to figure out what compiler is used.
* For now, complain if asked to use something other than Clang.

diff --git a/samex/bin/compile-samex-addon b/samex/bin/compile-samex-addon
--- a/samex/bin/compile-samex-addon
+++ b/samex/bin/compile-samex-addon
@@ -79,13 +79,30 @@ if [[ $? != 0 ]]; then
     exit 1
 fi
 
+# Set `$CC` to `"cc"` if it's not already set.
+if [[ ${CC} == '' ]]; then
+    CC='cc'
+fi
 
-CC=(cc -g)
+# Identify Clang vs. Gcc.
+WHAT_CC="$(
+    "${CC}" --version | awk '
+    /clang/ { print "clang"; exit 0; }
+    /gcc/   { print "gcc";   exit 0; }
+    END     { print "unknown" }
+    ')"
+
+if [[ ${WHAT_CC} != 'clang' ]]; then
+    echo 1>&2 "Sorry: Cannot use compiler: ${WHAT_CC}"
+    exit 1
+fi
+
+CC_PREFIX=("${CC}" -g)
 
 # Note: The GNU equivalent to `-dynamiclib` seems to be `-shared`, and
 # the equivalent to `-undefined dynamic_lookup` seems to be `-Ur`.
 COMPILE_LIB=(
-    "${CC[@]}"
+    "${CC_PREFIX[@]}"
         -dynamiclib -undefined dynamic_lookup
         -I"${includeDir}"
 )
